#!/bin/bash

# Initialize MySQL database.
# ADD this file into the container via Dockerfile.
# Assuming you specify a VOLUME ["/var/lib/mysql"] or `-v /var/lib/mysql` on the `docker run` command…
# Once built, do e.g. `docker run your_image /path/to/docker-mysql-initialize.sh`
# Again, make sure MySQL is persisting data outside the container for this to have any effect.

set -e
set -x

# Start the MySQL daemon in the background.
/usr/sbin/mysqld &
mysql_pid=$!

until mysqladmin ping &>/dev/null; do
  echo -n "."; sleep 0.2
done

# Permit root login without password from outside container.
mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'pass'"

mysql -u root -ppass < sno_rx_16ab_db/01_setup.sql
mysql -u root -ppass < sno_rx_16ab_db/02_load.sql

# Tell the MySQL daemon to shutdown.
mysqladmin shutdown

# Wait for the MySQL daemon to exit.
wait $mysql_pid

# set -e
# set -x

# mysql_install_db
# 

# # Start the MySQL daemon in the background.
# /usr/sbin/mysqld &
# mysql_pid=$!

# until mysqladmin ping >/dev/null 2>&1; do
#   echo -n "."; sleep 0.2
# done

# sudo mysql -u root -ppass
#     mysql> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'pass';
#     mysql> FLUSH PRIVILEGES;
#     mysql> EXIT;

# sudo mysql -u root -ppass < sno_rx_16ab_db/01_setup.sql
# sudo mysql -u root -ppass < sno_rx_16ab_db/02_load.sql
# sudo mysql -u root -ppass < sno_rx_16ab_db/03_load.sql
# sudo mysql -u root -ppass < sno_rx_16ab_db/04_load.sql
# sudo mysql -u root -ppass < sno_rx_16ab_db/05_load.sql
# sudo mysql -u root -ppass < sno_rx_16ab_db/06_load.sql
# sudo mysql -u root -ppass < sno_rx_16ab_db/07_load.sql
# sudo mysql -u root -ppass < sno_rx_16ab_db/08_load.sql


# RUN /bin/bash -c "/usr/bin/mysqld_safe --skip-grant-tables &" && \
#   sleep 5 && \
#   mysql -u root -ppass < sno_rx_16ab_db/01_setup.sql  && \
#   mysql -u root -ppass < sno_rx_16ab_db/02_load.sql && \
#   mysql -u root -ppass < sno_rx_16ab_db/03_load.sql && \
#   mysql -u root -ppass < sno_rx_16ab_db/04_load.sql && \
#   mysql -u root -ppass < sno_rx_16ab_db/05_load.sql && \
#   mysql -u root -ppass < sno_rx_16ab_db/06_load.sql && \
#   mysql -u root -ppass < sno_rx_16ab_db/07_load.sql && \
#   mysql -u root -ppass < sno_rx_16ab_db/08_load.sql 